import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainLayout from "./MainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = true

  return (
    <html lang="en">
      <body className={inter.className}>
        <MainLayout user={user}>
          {children}
        </MainLayout>
      </body>
    </html>
  );
}
